CLAUDE_API_KEY: 
GEMINI_API_KEY: AIzaSyD1iXEu6tHJQhrlHwJYmGtESYHzqRYNlMM
GROQ_API_KEY: 
OPENAI_API_KEY: sk-bv91dwOp68rpZVqbJW9DG7S8Ags6phRiLUgDyFIUkiFUt3gk
SERPER_API_KEY: c3f91096fa2ddd989369ec77ebeec74599d8644e
LLM_SHERPA_SERVER: http://localhost:5010/api/parseDocument?renderFormat=all&applyOcr=yes&useNewIndentParser=yes
NEO4J_URI: neo4j+s://8f98e2f2.databases.neo4j.io
NEO4J_USERNAME: neo4j
NEO4J_PASSWORD: 98lm2H-JNNMTl6kTT7H5RrQtWL_DPz4fLacZg64BxO4
AURA_INSTANCEID: 8f98e2f2
AURA_INSTANCENAME: Instance01