CLAUDE_API_KEY: 
GEMINI_API_KEY: 
GROQ_API_KEY: 
OPENAI_API_KEY: sk-bv91dwOp68rpZVqbJW9DG7S8Ags6phRiLUgDyFIUkiFUt3gk
SERPER_API_KEY: 
LLM_SHERPA_SERVER: http://localhost:5010/api/parseDocument?renderFormat=all&applyOcr=yes&useNewIndentParser=yes